### ISSUE TITLE
1.0 Milestone

### ISSUE THREAD

**Issue by jeremyrempel** [jeremyrempel/gitnotes#5]
P1:
- [ ] Enable configuring to different repos
- [ ] OAuth for private repos

P2:
- [ ] Enable editing/saving
- [ ] Offline support
- [ ] iOS feature parity

**Comment by rhythm1705** [comment]
Hi, I really like the idea of your app. Anyway I can contribute with the android development, documentation or anything else? And as I have never worked with cross platform code (only worked with android), how do I get started with the android part of the app?
Thanks.

**Comment by jeremyrempel** [comment]
Hey Rythm,

Any improvements to the app def appreciated! To get started with Android
just clone git repo and should just work in either IntelliJ or Android
Studio.

Thanks,
Jeremy
